const fs=require('fs'),path=require('path'),vm=require('vm');const root=__dirname;
const grammarRuntime=gm=>{const out={};for(const t of (gm.templates||[])){const opts=t.options||[];const reasons=opts.map((o,i)=>i===t.correctIndex?'Correct':((t.distractors||[]).find(d=>d.option===o)?.whyFails||'Distractor invalid'));(out[t.subskill]??=[]).push([t.stem,opts,t.correctIndex,t.explanation?.rule||t.pedagogicalObjective,reasons,t.cefr]);}return out};
const app=fs.readFileSync(path.join(root,'app.js'),'utf8');const V=JSON.parse(fs.readFileSync(path.join(root,'vocabulary-master.json'),'utf8'));const GM=JSON.parse(fs.readFileSync(path.join(root,'grammar-templates.json'),'utf8'));const G=grammarRuntime(GM);const R=JSON.parse(fs.readFileSync(path.join(root,'reading-bank.json'),'utf8'));
const elements={};const element=id=>elements[id] ||= {id,innerHTML:'',textContent:'',onclick:null,disabled:false,classList:{add(){},remove(){},toggle(){}},addEventListener(){},focus(){}};const document={baseURI:'http://localhost/',getElementById:element,querySelector(){return null},querySelectorAll(){return[]},createElement(){return {className:'',textContent:'',disabled:false,classList:{add(){},remove(){},toggle(){}},append(){},addEventListener(){}}}};const store={};const localStorage={getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=v,removeItem:k=>delete store[k]};const Notification=function(title,options){this.title=title;this.options=options;this.close=()=>{};};Notification.permission='granted';Notification.requestPermission=async()=>Notification.permission;const fetch=async u=>({ok:true,json:async()=>JSON.parse(fs.readFileSync(path.join(root,String(u).split('/').pop()),'utf8'))});const ctx={console,Notification,document,localStorage,fetch,location:{href:'http://localhost/'},window:{},self:{},Date,Math,URL,setTimeout,clearTimeout};ctx.window=ctx;ctx.self=ctx;ctx.window.scrollTo=()=>{};ctx.window.speechSynthesis={cancel(){},speak(){}};ctx.window.SpeechSynthesisUtterance=function(){};vm.createContext(ctx);vm.runInContext(app,ctx);
setTimeout(()=>{try{
let grammarBad=[];for(const [skill,arr] of Object.entries(G))for(const item of arr){for(let i=0;i<20;i++){const q=ctx.makeGrammarQuestion(skill,item);if(q.question!==item[0])grammarBad.push({skill,source:item[0],got:q.question});if(q.answerIndex<0||q.options.length!==4)grammarBad.push({skill,issue:'options'});}}
let vocabBad=[];const complete=V.filter(v=>v.status==='complete');for(let i=0;i<2000;i++){const v=complete[i%complete.length],q=ctx.makeVocabQuestion(v);if(q.answerIndex<0||q.answerIndex>=q.options.length||q.options.length<2)vocabBad.push({word:v.word,issue:'answer'});if(q.options.some(x=>!String(x).trim()))vocabBad.push({word:v.word,issue:'blank option'});if(q.skill==='vocabulary_synonym'&&q.options.some(x=>/\b(dan|yang|untuk|orang|sebuah|adalah|dengan)\b/i.test(String(x))))vocabBad.push({word:v.word,issue:'synonym contains Indonesian distractor',options:q.options});}
let readingMissing=0;for(const r of R)for(let i=0;i<r.qs.length;i++){const q=ctx.makeReadingQuestion(r,r.qs[i],i);if(!q.passage?.text)readingMissing++}
console.log(JSON.stringify({grammarBad:grammarBad.length,vocabBad:vocabBad.length,readingMissing},null,2));if(grammarBad.length||vocabBad.length||readingMissing)process.exitCode=1;
}catch(e){console.error(e);process.exitCode=1}},800)
