const fs=require('fs');const path=require('path');
const root=__dirname;const read=f=>JSON.parse(fs.readFileSync(path.join(root,f),'utf8'));
const norm=s=>String(s??'').toLowerCase().replace(/[^a-z0-9 ]+/g,' ').replace(/\s+/g,' ').trim();const qsig=q=>norm(q.question)+'||'+(q.options||[]).map(norm).sort().join('|');
const grammarRuntime=gm=>{const out={};for(const t of (gm.templates||[])){const opts=t.options||[];const reasons=opts.map((o,i)=>i===t.correctIndex?'Correct':((t.distractors||[]).find(d=>d.option===o)?.whyFails||'Distractor invalid'));(out[t.subskill]??=[]).push([t.stem,opts,t.correctIndex,t.explanation?.rule||t.pedagogicalObjective,reasons,t.cefr]);}return out};
const V=read('vocabulary-master.json'),R=read('reading-bank.json'),GM=read('grammar-templates.json'),G=grammarRuntime(GM);
const out={vocabulary:{total:V.length,unique:new Set(V.map(x=>String(x.word).toLowerCase().trim())).size,duplicates:0,duplicateWordLevelPos:0,missing:{meaning:0,example:0,phonetic:0,partOfSpeech:0},needsReview:0},reading:{passages:R.length,questions:R.reduce((n,x)=>n+(Array.isArray(x.qs)?x.qs.length:0),0),duplicatePassages:0,duplicateQuestions:0,duplicateOptions:0,invalidAnswers:0},grammar:{categories:Object.keys(G).length,items:Object.values(G).reduce((n,a)=>n+a.length,0),invalid:0},security:{aiApiReferences:0,apiKeyPatterns:0},architecture:{legacyVocabularyFileExists:fs.existsSync(path.join(root,'vocabulary.json')),masterRuntimeSource:true}};
const words=V.map(x=>String(x.word).toLowerCase().trim());out.vocabulary.duplicates=words.length-out.vocabulary.unique;const wordLevelPos=new Set(),wordLevelPosDup=new Set();for(const v of V){const k=[String(v.word).toLowerCase().trim(),String(v.level||v.cefr||''),String(v.partOfSpeech||'')].join('||');if(wordLevelPos.has(k))wordLevelPosDup.add(k);else wordLevelPos.add(k)}out.vocabulary.duplicateWordLevelPos=wordLevelPosDup.size;for(const v of V){const meaning=String(v.meaning||v.meanings?.[0]?.meaning||'').trim(),example=String(v.example||v.examples?.[0]?.en||'').trim();if(!meaning)out.vocabulary.missing.meaning++;if(!example)out.vocabulary.missing.example++;if(!String(v.phonetic||'').trim())out.vocabulary.missing.phonetic++;if(!String(v.partOfSpeech||'').trim())out.vocabulary.missing.partOfSpeech++;if(v.status!=='complete')out.vocabulary.needsReview++}
const pset=new Set(),qset=new Set();for(const r of R){const ps=norm(r.text);if(pset.has(ps))out.reading.duplicatePassages++;pset.add(ps);for(const q of (r.qs||[])){const x={question:q[0],options:q[1],answerIndex:q[2]};const s=qsig(x);if(qset.has(s))out.reading.duplicateQuestions++;qset.add(s);const opts=(q[1]||[]).map(norm);if(new Set(opts).size!==opts.length)out.reading.duplicateOptions++;if(!Number.isInteger(q[2])||q[2]<0||q[2]>=opts.length)out.reading.invalidAnswers++}}
for(const [k,arr] of Object.entries(G)){for(const q of arr){if(!Array.isArray(q)||typeof q[0]!=='string'||!Array.isArray(q[1])||!Number.isInteger(q[2])||q[2]<0||q[2]>=q[1].length||new Set(q[1].map(norm)).size!==q[1].length)out.grammar.invalid++}}
const runtimeFiles=['index.html','app.js','style.css','sw.js'];const txt=runtimeFiles.map(f=>fs.readFileSync(path.join(root,f),'utf8')).join('\n');out.security.aiApiReferences=(txt.match(/fetch\([^)]*(?:gemini|openai|anthropic|generativelanguage)|https?:\/\/[^\s'\"]*(?:openai|googleapis|anthropic)/gi)||[]).length;out.security.apiKeyPatterns=(txt.match(/AIza[0-9A-Za-z_-]{20,}|sk-[0-9A-Za-z_-]{20,}/g)||[]).length;out.architecture.legacyVocabularyFileExists=fs.existsSync(path.join(root,'vocabulary.json'));out.architecture.runtimeVocabularySource='vocabulary-master.json';
console.log(JSON.stringify(out,null,2));fs.writeFileSync(path.join(root,'AUDIT-REPORT.json'),JSON.stringify(out,null,2));
