/* FIEZEL Concept 01 — Spatial Dock + Classroom presentation bridge.
 * Capability/data source: FIEZEL-APPS main 626340630e28358c5757484535a2c0fc0e62eee8.
 * This sidecar preserves the CLONE recovery app.js and adds an iPhone-first shell.
 */
(function(root){
  'use strict';
  if(!root.document||root.__fiezelSpatialDockInstalled)return;
  root.__fiezelSpatialDockInstalled=true;

  var SOURCE_SHA='626340630e28358c5757484535a2c0fc0e62eee8';
  var PACK_URL='./features/classroom/classroom-lessons-v1.json';
  var app=root.document.getElementById('app');
  var baseGo=typeof root.go==='function'?root.go.bind(root):null;
  var activeCustom=false,packPromise=null,session=null,lastFeedback=null,currentVoicePair=null,voiceBusy=false,voiceToken=0;
  var sheet=null,backdrop=null;

  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c];});}
  function toast(text){try{if(typeof root.showToast==='function')return root.showToast(text);}catch(_){}console.info('[FIEZEL Spatial]',text);}
  function icons(){try{root.lucide&&root.lucide.createIcons&&root.lucide.createIcons({attrs:{'stroke-width':1.8,'aria-hidden':'true'}});}catch(_){}}
  function setApp(html){if(typeof root.setApp==='function')root.setApp(html);else if(app)app.innerHTML=html;icons();}
  function stopVoice(){voiceToken++;voiceBusy=false;try{root.FiezelVoiceRuntime&&root.FiezelVoiceRuntime.stop&&root.FiezelVoiceRuntime.stop();}catch(_){}setSpeaking(false);}
  function setSpeaking(on,label){var orb=root.document.getElementById('sdOrb'),wave=root.document.getElementById('sdWave'),title=root.document.getElementById('sdVoiceTitle'),hint=root.document.getElementById('sdVoiceHint');if(orb)orb.classList.toggle('speaking',!!on);if(wave)wave.classList.toggle('speaking',!!on);if(title&&label)title.textContent=label;if(hint)hint.textContent=on?'Materi boleh di-scroll. Voice Fiezel tetap di posisi ini.':'Ask, replay, atau lanjutkan materi di bawah.';}

  function ensureSheet(){
    if(sheet&&backdrop)return;
    backdrop=root.document.createElement('div');backdrop.className='sd-sheet-backdrop';backdrop.addEventListener('click',closeSheet);root.document.body.appendChild(backdrop);
    sheet=root.document.createElement('section');sheet.className='sd-sheet';sheet.setAttribute('role','dialog');sheet.setAttribute('aria-modal','true');root.document.body.appendChild(sheet);
  }
  function showSheet(kicker,title,body){ensureSheet();sheet.innerHTML='<div class="sd-grab"></div><div class="sd-sheet-head"><div><small>'+esc(kicker)+'</small><h2>'+esc(title)+'</h2></div><button type="button" class="sd-sheet-close" data-sd-close aria-label="Tutup">×</button></div>'+body;sheet.querySelector('[data-sd-close]').addEventListener('click',closeSheet);backdrop.classList.add('open');sheet.classList.add('open');icons();}
  function closeSheet(){if(sheet)sheet.classList.remove('open');if(backdrop)backdrop.classList.remove('open');}

  function route(view){closeSheet();activeCustom=false;stopVoice();if(!baseGo)return false;var ok=baseGo(view);setTimeout(function(){syncDock();enhanceHome();},40);return ok;}
  function item(icon,title,sub,action){return '<button class="sd-item" type="button" data-sd-action="'+esc(action)+'"><span class="sd-item-icon"><i data-lucide="'+esc(icon)+'"></i></span><span><b>'+esc(title)+'</b><small>'+esc(sub)+'</small></span></button>';}
  function wireSheetActions(){if(!sheet)return;sheet.querySelectorAll('[data-sd-action]').forEach(function(btn){btn.addEventListener('click',function(){var a=btn.dataset.sdAction;if(a==='classroom')openClassroom();else if(a==='settings')openSettings();else if(a==='diagnostics')openDiagnostics();else if(a==='voice')openVoice();else route(a);});});}
  function openLearn(){showSheet('LEARN','Pilih skill tanpa scroll panjang','<div class="sd-grid">'+[
    item('book-a','Vocabulary','Recall, meaning, usage','vocab'),item('braces','Grammar','Pattern + focused practice','grammar'),item('book-open-text','Reading','Evidence-based comprehension','reading'),item('audio-waveform','Speaking + Listening','72 latihan A1–C2','skills'),item('sparkles','FIEZEL Classroom','Adaptive Tutor + Smart Board','classroom'),item('clipboard-check','Placement','150 soal pemetaan','test'),item('chart-no-axes-combined','Evidence / Peta','Progress yang dapat dijelaskan','progress'),item('sliders-horizontal','Settings','Voice, accessibility, preferences','settings')
  ].join('')+'</div>');wireSheetActions();}
  function openMe(){showSheet('JAHRAN · PERSONAL OS','Profile & system','<div class="sd-grid">'+[
    item('chart-no-axes-combined','Learning evidence','Peta, mastery, due review','progress'),item('sliders-horizontal','Settings','Haptics, motion, notification','settings'),item('volume-2','Voice / Offline','Neural bundle & test voice','voice'),item('stethoscope','Diagnostics','Device + pipeline health','diagnostics')
  ].join('')+'</div><p style="color:#718096;font-size:.72rem;line-height:1.5;margin:12px 2px 0">FIEZEL tetap single-user untuk Jahran. Raw microphone audio tidak dijadikan learner evidence secara default.</p>');wireSheetActions();}
  function openSettings(){closeSheet();try{if(typeof root.openSettings==='function')root.openSettings();else toast('Settings belum tersedia.');}catch(_){toast('Settings belum tersedia.');}}
  function openVoice(){closeSheet();try{if(typeof root.openSettings==='function'){root.openSettings();setTimeout(function(){var el=root.document.querySelector('.voice-setup-card');el&&el.scrollIntoView({behavior:'smooth',block:'center'});},160);}else toast('Voice setup belum tersedia.');}catch(_){toast('Voice setup belum tersedia.');}}
  function openDiagnostics(){closeSheet();var btn=Array.from(root.document.querySelectorAll('button')).find(function(b){return /diagnostic/i.test(String(b.textContent||''));});if(btn){btn.click();return;}toast('Panel diagnostics belum terdeteksi pada build ini.');}

  function installDock(){
    var nav=root.document.querySelector('.bottomnav');if(!nav)return;
    nav.innerHTML=''+
      '<button type="button" class="nav" data-view="home" data-sd-nav="home"><i data-lucide="house"></i><span>Home</span></button>'+
      '<button type="button" class="nav" data-sd-nav="learn"><i data-lucide="layers-3"></i><span>Learn</span></button>'+
      '<button type="button" class="nav sd-tutor" data-sd-nav="classroom"><i data-lucide="sparkles"></i><span>Tutor</span></button>'+
      '<button type="button" class="nav" data-view="progress" data-sd-nav="progress"><i data-lucide="chart-no-axes-combined"></i><span>Evidence</span></button>'+
      '<button type="button" class="nav" data-sd-nav="me"><i data-lucide="circle-user-round"></i><span>Me</span></button>';
    nav.querySelector('[data-sd-nav="home"]').addEventListener('click',function(){route('home');});
    nav.querySelector('[data-sd-nav="learn"]').addEventListener('click',openLearn);
    nav.querySelector('[data-sd-nav="classroom"]').addEventListener('click',openClassroom);
    nav.querySelector('[data-sd-nav="progress"]').addEventListener('click',function(){route('progress');});
    nav.querySelector('[data-sd-nav="me"]').addEventListener('click',openMe);
    icons();syncDock();
  }
  function syncDock(){var nav=root.document.querySelector('.bottomnav');if(!nav)return;nav.querySelectorAll('.nav').forEach(function(b){b.classList.remove('active');});if(activeCustom){nav.querySelector('[data-sd-nav="classroom"]')?.classList.add('active');return;}var view='';try{view=root.state&&root.state.view||'';}catch(_){}nav.querySelector('[data-view="'+view+'"]')?.classList.add('active');if(['vocab','grammar','reading','skills','test'].includes(view))nav.querySelector('[data-sd-nav="learn"]')?.classList.add('active');}

  function recommendedText(){var due=0,ready=false;try{ready=!!root.state?.adaptiveReady;due=typeof root.getDueReviewCount==='function'?root.getDueReviewCount():0;}catch(_){}return{title:ready?'Mulai next-best action':'Bangun fondasi, satu sesi dulu',body:due?due+' materi menunggu review. Classroom akan menjelaskan dulu sebelum micro-check.':'FIEZEL memilih satu fokus utama agar Home tetap pendek di iPhone.'};}
  function enhanceHome(){var home=root.document.querySelector('.home-page');if(!home||home.dataset.sdEnhanced)return;home.dataset.sdEnhanced='1';var r=recommendedText(),mission=root.document.createElement('section');mission.className='sd-home-mission';mission.innerHTML='<small>NEXT BEST ACTION</small><h2>'+esc(r.title)+'</h2><p>'+esc(r.body)+'</p><div class="sd-home-actions"><button class="sd-main" type="button">Start with Fiezel</button><button class="sd-why" type="button">Why?</button></div>';mission.querySelector('.sd-main').addEventListener('click',openClassroom);mission.querySelector('.sd-why').addEventListener('click',function(){showSheet('WHY THIS NOW?','FIEZEL memilih berdasarkan evidence','<p style="color:#55657a;line-height:1.6">Prioritas memakai learner evidence, review jatuh tempo, dan weakness yang sudah terukur. Engagement tidak dianggap sebagai mastery.</p>');});home.insertBefore(mission,home.firstChild);
    var launcher=home.querySelector('.learning-launcher');if(launcher&&!launcher.querySelector('.sd-classroom-launch')){var b=root.document.createElement('button');b.type='button';b.className='launch-card skills-launch sd-classroom-launch';b.innerHTML='<span class="launch-icon"><i data-lucide="sparkles"></i></span><span><small>Adaptive Tutor</small><b>FIEZEL Classroom</b><em>Teaching beat, Smart Board, Ask Fiezel.</em></span><i data-lucide="arrow-up-right"></i>';b.addEventListener('click',openClassroom);launcher.appendChild(b);icons();}}

  async function loadPack(){if(packPromise)return packPromise;packPromise=fetch(PACK_URL,{cache:'no-store'}).then(function(r){if(!r.ok)throw new Error('classroom_pack_'+r.status);return r.json();}).then(function(pack){if(pack.schema!=='fiezel-classroom-lessons-v1')throw new Error('classroom_schema');return pack;});return packPromise;}
  function voiceMarkup(title,hint){return '<section class="sd-voice-fixed"><div class="sd-orb" id="sdOrb"></div><div class="sd-voice-copy"><small>FIEZEL · LIVE VOICE</small><h2 id="sdVoiceTitle">'+esc(title||'Fiezel is ready.')+'</h2><p id="sdVoiceHint">'+esc(hint||'Voice tetap di sini saat materi di-scroll.')+'</p><div class="sd-wave" id="sdWave">'+new Array(18).fill('<i></i>').join('')+'</div></div></section>';}
  function classroomShell(inner,title){return '<section class="sd-classroom"><header class="sd-classroom-head"><div><small>FIEZEL CLASSROOM · APPS MAIN</small><h1>'+esc(title||'Classroom')+'</h1></div><button type="button" data-sd-subjects>Subjects</button></header>'+voiceMarkup('Fiezel is ready.','Voice presence tetap fixed saat lesson di-scroll.')+'<div class="sd-lesson-scroll">'+inner+'</div></section>';}
  function wireSubjects(){root.document.querySelector('[data-sd-subjects]')?.addEventListener('click',renderCategories);}
  async function openClassroom(){closeSheet();stopVoice();activeCustom=true;syncDock();setApp('<section class="sd-classroom"><div style="padding:32px" class="card"><b>Loading FIEZEL Classroom…</b><p>Reading synced APPS lesson pack.</p></div></section>');try{var pack=await loadPack();session=root.FiezelClassroom.createSession(pack);lastFeedback=null;renderCategories();}catch(e){setApp('<div class="card"><b>Classroom belum dapat dibuka.</b><p>'+esc(e.message||e)+'</p></div>');}}
  function renderCategories(){stopVoice();activeCustom=true;var cats=session.categories();var cards=cats.map(function(c){var n=session.lessonsIn(c.id).length;return '<button type="button" class="sd-category" data-sd-cat="'+esc(c.id)+'"><b>'+esc(c.label)+'</b><small>'+esc(c.hint||'')+' · '+(n?n+' lesson':'route')+'</small></button>';}).join('');setApp(classroomShell('<div class="sd-category-grid">'+cards+'</div><p style="color:#718096;font-size:.76rem;line-height:1.55;margin-top:10px">Satu objective pada satu waktu. Listening dan Speaking tetap memakai Skills Lab agar tidak menduplikasi latihan.</p>','Choose a subject'));wireSubjects();root.document.querySelectorAll('[data-sd-cat]').forEach(function(b){b.addEventListener('click',function(){var id=b.dataset.sdCat,lessons=session.lessonsIn(id);if(!lessons.length){if(id==='listening'||id==='speaking'){route('skills');return;}toast('Classroom '+id+' masih roadmap.');return;}session.chooseCategory(id);renderTopics();});});}
  function renderTopics(){stopVoice();var snap=session.snapshot(),lessons=session.lessonsIn(snap.categoryId),buttons=lessons.map(function(l){return '<button type="button" class="sd-category" data-sd-lesson="'+esc(l.id)+'"><b>'+esc(l.topic)+'</b><small>'+esc(l.level||'')+' · open micro-lesson</small></button>';}).join('');setApp(classroomShell('<div class="sd-category-grid">'+buttons+'</div>',snap.categoryId||'Topics'));wireSubjects();root.document.querySelectorAll('[data-sd-lesson]').forEach(function(b){b.addEventListener('click',function(){session.chooseLesson(b.dataset.sdLesson);lastFeedback=null;renderTeach(true);});});}
  function boardMarkup(board){board=board||{};var lines=(board.examples||[]).map(function(x,i){return '<div class="sd-board-line" id="sdBoardLine'+i+'">• '+esc(x)+'</div>';}).join('');return '<section class="sd-board"><small>SMART BOARD</small><h2>'+esc(board.title||'Lesson')+'</h2>'+(board.formula?'<div class="sd-formula">'+esc(board.formula)+'</div>':'')+'<div class="sd-board-list">'+lines+'</div></section>';}
  function teacherControls(){return '<div class="sd-controls"><button type="button" data-sd-ask>💬 Ask</button><button type="button" data-sd-confused>⇄ Confused</button><button type="button" data-sd-slower>🐌 Slower</button><button type="button" data-sd-replay>↻ Replay</button></div>';}
  function wireTeacherControls(pair){root.document.querySelector('[data-sd-ask]')?.addEventListener('click',openAsk);root.document.querySelector('[data-sd-confused]')?.addEventListener('click',confused);root.document.querySelector('[data-sd-slower]')?.addEventListener('click',function(){speak(pair,.72);});root.document.querySelector('[data-sd-replay]')?.addEventListener('click',function(){speak(pair,1);});}
  function renderTeach(autoSpeak){stopVoice();var snap=session.snapshot(),seg=session.currentSegment(),lesson=session.lesson();if(!seg){renderQuiz();return;}var feedback=lastFeedback?'<div class="sd-feedback">'+esc(lastFeedback)+'</div>':'';var inner=boardMarkup(lesson.board)+'<div class="sd-caption" id="sdCaption">'+esc(seg.en)+'</div><div class="sd-subtitle" id="sdSubtitle">'+esc(seg.id)+'</div>'+feedback+teacherControls()+'<button class="sd-next" type="button" data-sd-next>'+(snap.segmentIndex>=snap.segmentCount-1?'Start practice':'Continue')+' →</button>';setApp(classroomShell(inner,lesson.topic));wireSubjects();wireTeacherControls(seg);root.document.querySelector('[data-sd-next]')?.addEventListener('click',function(){stopVoice();session.nextSegment();lastFeedback=null;if(session.snapshot().phase==='quiz')renderQuiz();else renderTeach(true);});if(autoSpeak)speak(seg,1);}
  function renderQuiz(){stopVoice();var snap=session.snapshot(),q=session.currentQuestion(),lesson=session.lesson();if(!q){renderSummary();return;}var options=q.options.map(function(o,i){return '<button type="button" data-sd-answer="'+i+'">'+esc(o)+'</button>';}).join('');var feedback=lastFeedback?'<div class="sd-feedback">'+esc(lastFeedback)+'</div>':'';var board=lastFeedback?{title:'Adaptive feedback',formula:snap.remediating?'Try another route':'Evidence update',examples:[lastFeedback]}:{title:lesson.topic,formula:'Question '+(snap.questionIndex+1)+' / '+snap.questionCount,examples:[]};setApp(classroomShell(boardMarkup(board)+'<div style="padding:11px 2px 3px"><small style="color:#2867d8;font-weight:850;letter-spacing:.11em">CHECK UNDERSTANDING</small><h2 style="margin:.35rem 0">'+esc(q.prompt)+'</h2><div class="sd-options">'+options+'</div>'+feedback+'</div>'+teacherControls(),lesson.topic));wireSubjects();wireTeacherControls(q.explain);root.document.querySelectorAll('[data-sd-answer]').forEach(function(b){b.addEventListener('click',function(){var out=session.answer(Number(b.dataset.sdAnswer));var fb=out.result.feedback||{};lastFeedback=(out.result.correct?'Correct. ':'Let’s repair it. ')+(fb.en||'')+' '+(fb.id||'');if(out.snapshot.phase==='summary')renderSummary();else renderQuiz();});});}
  function renderSummary(){stopVoice();var snap=session.snapshot(),lesson=session.lesson();setApp(classroomShell('<div class="card" style="text-align:center;padding:24px"><small style="color:#2867d8;font-weight:850">LESSON COMPLETE</small><div style="font-size:4rem;font-weight:900;letter-spacing:-.07em;color:#2867d8">'+snap.scorePercent+'%</div><h2>'+esc(lesson?.topic||'Classroom')+'</h2><p>'+snap.correct+' first-pass correct · '+snap.attempts+' attempts.</p><button type="button" class="primary" data-sd-done>Choose another subject</button></div>',lesson?.topic||'Classroom'));wireSubjects();root.document.querySelector('[data-sd-done]')?.addEventListener('click',renderCategories);}

  function revealBoard(){root.document.querySelectorAll('.sd-board-line').forEach(function(line,i){setTimeout(function(){line.classList.add('show');},360+i*430);});}
  async function speak(pair,speed){if(!pair)return;stopVoice();currentVoicePair=pair;var token=++voiceToken,caption=root.document.getElementById('sdCaption'),subtitle=root.document.getElementById('sdSubtitle');setSpeaking(true,'Fiezel is explaining…');voiceBusy=true;revealBoard();if(caption)caption.textContent=pair.en||'';if(subtitle)subtitle.textContent=pair.id||pair.idText||'';try{var runtime=root.FiezelVoiceRuntime;if(!runtime||typeof runtime.speak!=='function')throw new Error('neural_runtime_unavailable');var status=typeof runtime.status==='function'?runtime.status():null;if(status&&status.prepared===false)throw new Error('neural_voice_not_downloaded');await runtime.speak(String(pair.en||''),{voice:typeof root.neuralVoiceFor==='function'?root.neuralVoiceFor({}):undefined,lang:'en-US',speed:Math.max(.55,Math.min(1.15,(typeof root.selectedNeuralRate==='function'?Number(root.selectedNeuralRate())||1:1)*(speed||1))),allowFallback:false});if(token!==voiceToken)return;setSpeaking(false,'Explanation complete.');}catch(e){if(token!==voiceToken)return;setSpeaking(false,'Text lesson ready.');var hint=root.document.getElementById('sdVoiceHint');if(hint)hint.textContent='Neural voice belum siap ('+String(e.message||e)+'). Lesson state tetap aman.';}finally{if(token===voiceToken)voiceBusy=false;}}
  function confused(){stopVoice();var board=root.document.querySelector('.sd-board');if(!board)return;board.innerHTML='<small>STRATEGY SWITCH · TIMELINE</small><h2>Let’s see it another way.</h2><div class="sd-formula">PAST ─────●────→ NOW</div><div class="sd-board-list"><div class="sd-board-line show">• action happened before now</div><div class="sd-board-line show">• result is still connected to now</div></div>';lastFeedback='FIEZEL changed strategy instead of repeating the same explanation.';speak({en:"Let's put it on a timeline. The action happened before now, but the result is still connected to the present.",id:'Kita taruh di garis waktu. Kejadiannya sebelum sekarang, tetapi hasilnya masih terhubung dengan masa kini.'},.88);}
  function answerSideQuestion(q){var low=String(q||'').toLowerCase();if(/went|gone|v2|v3/.test(low))return{en:'Went is the normal past form. After have or has, English needs the third form: gone.',id:'Went adalah bentuk lampau biasa. Setelah have atau has, gunakan bentuk ketiga: gone.'};if(/have|has/.test(low))return{en:'Use has with he, she and it. Use have with I, you, we and they.',id:'Gunakan has untuk he, she, it; gunakan have untuk I, you, we, they.'};return{en:'The useful question is whether the earlier action is still connected to the situation now.',id:'Pertanyaan utamanya: apakah kejadian sebelumnya masih terhubung dengan situasi sekarang?'};}
  function openAsk(){stopVoice();showSheet('ASK FIEZEL','Checkpoint tetap tersimpan','<textarea class="sd-ask" id="sdAskText" maxlength="240" placeholder="Contoh: Why can’t I say I have went?"></textarea><button type="button" class="sd-next" style="margin-top:8px" id="sdAskSend">Ask without leaving lesson</button>');root.document.getElementById('sdAskSend').addEventListener('click',function(){var q=String(root.document.getElementById('sdAskText').value||'').trim();if(!q)return;var ans=answerSideQuestion(q);closeSheet();lastFeedback='Ask Fiezel: '+ans.en+' '+ans.id;var box=root.document.querySelector('.sd-feedback');if(box)box.textContent=lastFeedback;else{var controls=root.document.querySelector('.sd-controls');if(controls){box=root.document.createElement('div');box.className='sd-feedback';box.textContent=lastFeedback;controls.before(box);}}speak(ans,.9);});setTimeout(function(){root.document.getElementById('sdAskText')?.focus();},80);}

  root.go=function(v){if(v==='classroom')return openClassroom();if(v==='learn'){openLearn();return true;}if(v==='me'){openMe();return true;}return route(v);};
  root.FiezelSpatial=Object.freeze({version:'spatial-dock-v1',sourceSha:SOURCE_SHA,openLearn:openLearn,openMe:openMe,openClassroom:openClassroom,closeSheet:closeSheet});
  root.document.documentElement.classList.add('fiezel-spatial-v1');
  installDock();ensureSheet();enhanceHome();
  var observer=new MutationObserver(function(){requestAnimationFrame(function(){if(!activeCustom){enhanceHome();syncDock();}});});if(app)observer.observe(app,{childList:true,subtree:false});
  root.addEventListener('pagehide',stopVoice);
})(typeof globalThis!=='undefined'?globalThis:this);
